string(TIMESTAMP COMPILE_TIME %Y%m%d_%H%M%S)
set(BUILD_TIME ${COMPILE_TIME})

find_package(Git)

# get branch
execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE  GIT_REPO_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE)

# get commit Hash
execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE  GIT_REPO_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE)

if(${GIT_REPO_BRANCH} MATCHES "^v([1-9]+)\\.([1-9]+)\\.([1-9]+)$")
    SET(LIB_DEC_VERSION_MAJOR ${CMAKE_MATCH_1})
    SET(LIB_DEC_VERSION_MINOR ${CMAKE_MATCH_2})

    SET(LIB_ENC_VERSION_MAJOR ${CMAKE_MATCH_1})
    SET(LIB_ENC_VERSION_MINOR ${CMAKE_MATCH_2})

    SET(VERSION_BUILD ${CMAKE_MATCH_3})
    message("VERSION FULL: ${LIB_DEC_VERSION_MAJOR}.${LIB_DEC_VERSION_MINOR}.${VERSION_BUILD}")
elseif(${GIT_REPO_BRANCH} MATCHES "^v([1-9]+)\\.([1-9]+)$")
    SET(LIB_DEC_VERSION_MAJOR ${CMAKE_MATCH_1})
    SET(LIB_DEC_VERSION_MINOR ${CMAKE_MATCH_2})

    SET(LIB_ENC_VERSION_MAJOR ${CMAKE_MATCH_1})
    SET(LIB_ENC_VERSION_MINOR ${CMAKE_MATCH_2})

    SET(VERSION_BUILD 0)
    message("VERSION PARTIAL: ${LIB_DEC_VERSION_MAJOR}.${LIB_DEC_VERSION_MINOR}")
else()
    SET(LIB_DEC_VERSION_MAJOR 0)
    SET(LIB_DEC_VERSION_MINOR 0)

    SET(LIB_ENC_VERSION_MAJOR 0)
    SET(LIB_ENC_VERSION_MINOR 0)

    SET(VERSION_BUILD 0)

    message("VERSION NULL: ${LIB_DEC_VERSION_MAJOR}.${LIB_DEC_VERSION_MINOR}.${VERSION_BUILD}")
endif()

set(lib_version_STRING "\"${GIT_REPO_BRANCH}-${GIT_REPO_HASH}-${BUILD_TIME}\"")
message("VERSION STRING: ${lib_version_STRING}")
