execute_process (COMMAND hostname OUTPUT_VARIABLE hostname OUTPUT_STRIP_TRAILING_WHITESPACE)

if (NOT DEFINED SOURCE_TREE)
    message (FATAL_ERROR "please specify -DSOURCE_TREE=")
endif ()

set(CTEST_SOURCE_DIRECTORY "${SOURCE_TREE}")
set(CTEST_BINARY_DIRECTORY "${SOURCE_TREE}/build")

set(CTEST_SITE "${hostname}")
set(CTEST_CMAKE_GENERATOR "cmake")
set(CTEST_COVERAGE_COMMAND "gcov")
set(CTEST_BUILD_NAME "lowlevel_dynamic_analysis")
set(CTEST_LABELS_FOR_SUBPROJECTS "lowlevel_dynamic_analysis")
execute_process (COMMAND bash -c "rm -rf dmesg_log.txt && touch dmesg_log.txt")
set(CTEST_NOTES_FILES "dmesg_log.txt")
set(CTEST_CUSTOM_MAXIMUM_PASSED_TEST_OUTPUT_SIZE 5000000)
set(CTEST_CUSTOM_MAXIMUM_FAILED_TEST_OUTPUT_SIZE 5000000)
set(TEST_PASS "0")
set(TEST_SKIP "0")
set(TEST_FAIL "0")
set(TEST_COST "0")
set(CASE_COST "0")
find_program(CTEST_MEMORYCHECK_COMMAND NAMES valgrind)
set(CTEST_MEMORYCHECK_TYPE Valgrind)
set(CTEST_MEMORYCHECK_COMMAND_OPTIONS "--errors-for-leak-kinds=all --show-leak-kinds=all --leak-check=full --error-exitcode=1")
set(CTEST_CONFIGURATION_TYPE "Debug")
#set(CTEST_MEMORYCHECK_SUPPRESSIONS_FILE ${CTEST_SOURCE_DIRECTORY}/ut/static_check/valgrind.supp)

set(CTEST_NIGHTLY_START_TIME "15:11:13 UTC")
ctest_start("Continuous")
ctest_submit(PARTS Notes SUBMIT_URL http://192.168.30.90:32181/submit.php?project=unitest RETURN_VALUE submit_result)
string(TIMESTAMP _begin_test "%s")
message("Test .......")
string(TIMESTAMP _begin_case "%s")

ctest_memcheck(INCLUDE unitest RETURN_VALUE test_result CAPTURE_CMAKE_ERROR cmake_err)
execute_process (COMMAND bash -c "dmesg -T >> dmesg_log.txt")
ctest_submit(PARTS Update SUBMIT_URL http://192.168.30.90:32181/submit.php?project=unitest RETURN_VALUE submit_result)
string(TIMESTAMP _end_case "%s")
math(EXPR CASE_COST "${_end_case} - ${_begin_case}")
#ctest_submit(PARTS Test SUBMIT_URL http://192.168.30.90:32181/submit.php?project=unitest RETURN_VALUE submit_result)
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "192.168.30.90:32181")
set(CTEST_DROP_LOCATION "/submit.php?project=unitest")
ctest_submit()